pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }

            steps {
                dir('bugtracker-backend') {
                    withEnv([
                        'HOME=/tmp',
                        'GOCACHE=/tmp/go-build',
                        'GOPATH=/tmp/go'
                    ]) {
                    sh 'go test -v ./...'
                    }
                }
            }
        }
    }
}